### ISSUE TITLE
Erreur sur distrib_discrete : pas de $test.stat donc pas d'export

### ISSUE THREAD

**Issue by tdelc** [jgires/fonctionr#1]
La fonction discrete_discrete ne génère pas de test stat, ce qui est plutôt logique, mais du coup, cela génère une erreur dans l'export sous Excel.

![image](https://github.com/user-attachments/assets/b57ce94f-eb20-464d-93a1-62bc930338dc)

**Comment by jgires** [comment]
Super, merci beaucoup pour avoir fait remonter ça, je règle ça tout de suite !

**Comment by jgires** [comment]
Voilà, c'est réglé. Peux-tu tester pour voir si tout est OK ? (Il faut réinstaller le package pour avoir la MAJ)
Juste pour info, il est possible de réaliser un test khi2 d'adéquation avec `distrib_discrete()`.
L'export prévu doit également être en format Excel (avec l'extension `.xlsx` et non `.csv`).

**Comment by tdelc** [comment]
Parfait, ça fonctionne ! Alors, en fait, le .csv fonctionne, car Excel arrive à faire le travail, mais en effet, cela génère une erreur. merci beaucoup !
